apiVersion: v1
kind: Service
metadata:
  name: calculator-service
spec:
  type: LoadBalancer
  selector:
    app: calculator
  ports:
    - protocol: TCP
      port: 8089         # Port externe (accessible depuis l'extérieur)
      targetPort: 9001   # Port interne du conteneur (Tomcat écoute sur ce port)
