apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
      - name: calculator
        image: calculator # L'image que nous avons construite
        imagePullPolicy: IfNotPresent # Ajoute cette ligne
        ports:
        - containerPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: calculator-service
spec:
  type: NodePort
  selector:
    app: calculator
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001
      nodePort: 30007 # Port exposé par Minikube sur ta machine
