config:
  platform: linux
  image_resource:
    type: docker-image
    source:
      repository: maven
      tag: 3.8.6-openjdk-17  # Image avec Maven et OpenJDK 17
  inputs:
    - name: calculator-repo  # Utilise la sortie de la tâche précédente
  run:
    path: sh
    args:
      - -exc
      - |
        cd calculator-repo  # Accède au répertoire cloné qui est maintenant monté en entrée
        echo "Building project..."
        ls -la  # Vérifie le contenu du répertoire cloné
        # Ajoutez vos commandes de build ici, par exemple :
        # ./mvn clean install