platform: linux
image_resource:
  type: registry-image
  source:
    repository: openjdk:11
inputs:
  - name: build-output
run:
  path: sh
  args:
    - -exc
    - |
      echo "Running tests on build artefact..."
      java -jar build-output/calculator.jar --test
