resources:
  - name: calculator-repo
    type: git
    source:
      uri: https://github.com/your-repo/calculator.git
      branch: develop

jobs:
  - name: build
    plan:
      - get: calculator-repo
        trigger: true
      - task: clone-calculator-repo
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: concourse/git-resource
              tag: latest
          params:
            REPO_URI: https://github.com/robelkend/cicd-testing-java-cours.git
            BRANCH: develop
          outputs:
            - name: calculator-repo  # Déclare le répertoire comme sortie
          run:
            path: sh
            args:
              - -exc
              - |
                echo "Cloning repository..."
                git config --global --add safe.directory /tmp/calculator-repo
                git clone --branch "$BRANCH" "$REPO_URI" calculator-repo  # Cloner dans le bon répertoire
                echo "Repository cloned successfully"
                ls -la calculator-repo  # Vérifie le contenu cloné dans le répertoire de sortie

      - task: build
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: maven
              tag: 3.8-openjdk-17
          inputs:
            - name: calculator-repo  # Utilise la sortie de la tâche précédente
          run:
            path: sh
            args:
              - -exc
              - |
                cd calculator-repo  # Accède au répertoire cloné qui est maintenant monté en entrée
                echo "Building project..."
                ls -la  # Vérifie le contenu du répertoire cloné
                # Ajoutez vos commandes de build ici, par exemple :
                mvn clean install
